//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamlicaProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresBilgileri
    {
        public int adresId { get; set; }
        public string adres { get; set; }
        public Nullable<int> kullaniciId { get; set; }
    
        public virtual kullaniciBilgileri kullaniciBilgileri { get; set; }
    }
}
